name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      env:
        scope: ${{ secrets.Scope }} 
        access_token: ${{ secrets.AccessToken }}
        refresh_token: ${{ secrets.RefreshToken }}
        name: ${{ secrets.Name }}
        userId: ${{ secrets.UserId }}
        client_id: ${{ secrets.ClientId }}
        client_secret: ${{ secrets.ClientSecret }}
      run: dotnet test --no-restore --verbosity normal
